source 'https://rubygems.org'

gem 'rails', '~> 3.2.3'

gem 'sqlite3'
gem "fastercsv"
gem "twitter"
gem "amee"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem "rspec"
  gem "rspec-rails"
end